version: '3'

volumes:
  db-data:
    external: false

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "3307:3306"
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/hiking_trails_challenge
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
