version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: hiking_trails_challenge
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ".:/hiking_trails_challenge"
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_NAME: hiking_trails_challenge
      DB_USERNAME: docker
      DB_PASSWORD: docker
      DB_HOST: db
