default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: hiking_trails_challenge_development

test:
  <<: *default
  database: hiking_trails_challenge_test

production:
  <<: *default
  database: hiking_trails_challenge_production
