default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST '] %>

development: 
  <<: *default
  database: hiking_trails_challenge_development

test:
  <<: *default
  database: hiking_trails_challenge_test

production:
  <<: *default
  database: hiking_trails_challenge_production
