hike_1 = Hike.create(name: "Hike 1", vote_count: 5)
hike_2 = Hike.create(name: "Hike 2", vote_count: 10)
hike_3 = Hike.create(name: "Hike 3", vote_count: 15)
hike_4 = Hike.create(name: "Hike 4", vote_count: 20)
hike_5 = Hike.create(name: "Hike 5", vote_count: 25)
